print('Tabela-Verdade do OU')
print(True, 'ou', True, '=', (True or True))
print(True, 'ou', False, '=', (True or False))
print(False, 'ou', True, '=', (False or True))
print(False, 'ou', False, '=', (False or False))
print('')
print('Tabela-Verdade do NOT')
print('Não', True, '=', (not True))
print('Não', False, '=', (not False))
